=== freshehrteam/GEL/docs/cancer/original datasets/Cancer Schemas v2.0.0 FINAL/InterventionsCancer-v2.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:vc='http://www.w3.org/2007/XMLSchema-versioning' xmlns:gelCAN='https://genomicsengland.co.uk/xsd/cancer/2.0.0' xmlns='https://genomicsengland.co.uk/xsd/cancer/2.0.0' targetNamespace='https://genomicsengland.co.uk/xsd/cancer/2.0.0' vc:minVersion='1.1' elementFormDefault='qualified'>
  <xs:annotation>
    <xs:documentation>
      <h1>InterventionsCancer</h1>
      <p>Version:2.0.0</p>
      <p>Description:Main Programme Cancer Interventions Schemas</p>
      <p>Generated: 2016-01-25T16:49:04.594+0000</p>
    </xs:documentation>
  </xs:annotation>
  <xs:element name='interventions'>
    <xs:complexType>
      <xs:sequence>
        <xs:element name='metadata' type='metadata' minOccurs='1' maxOccurs='1' />
        <xs:element name='subject' type='subject-29955.2' minOccurs='1' maxOccurs='unbounded' />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name='metadata'>
    <xs:sequence>
      <xs:element name='schema-name' minOccurs='1' maxOccurs='1'>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:enumeration value='InterventionsCancer' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name='schema-version' minOccurs='1' maxOccurs='1'>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:enumeration value='2.0.0' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name='date' type='xs:date' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>The date that this file was generated</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='source-organisation' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>ODS code of the source organisation within the GMC sending the message</p>
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:minLength value='1' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name='source-system' type='xs:string' minOccurs='0' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Source system. Optional but may be used to supply source with information if there are any issues with the submitted XML.</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='local-report-id' type='xs:string' minOccurs='0' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Source system report Id. Optional but may be used to supply source with information if there are any issues with the submitted XML.</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name='subject-29955.2'>
    <xs:sequence>
      <xs:element name='participant-identifiers' type='participant-identifiers-29330.2' minOccurs='1' maxOccurs='1' />
      <xs:element name='surgery' type='surgery-29956.2' minOccurs='0' maxOccurs='unbounded' />
      <xs:element name='systemic-anti-cancer-therapy' type='systemic-anti-cancer-therapy-29957.2' minOccurs='0' maxOccurs='unbounded' />
      <xs:element name='radiotherapy' type='radiotherapy-29959.2' minOccurs='0' maxOccurs='unbounded' />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name='participant-identifiers-29330.2'>
    <xs:sequence>
      <xs:element name='participant-id' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Participant Identifier (supplied by Genomics England)</p>
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:minLength value='1' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name='date-of-birth' type='xs:date' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>The participant&amp;apos;s date of birth</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='nhs-number' type='nhsnumber-12817.1' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Validated NHS number for participant</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='chi-number' type='xs:string' minOccurs='0' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Scottish Community Health Index (CHI) number for participant</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='surname' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>The participant&amp;apos;s surname</p>
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:minLength value='1' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name='forenames' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>The participant&amp;apos;s forenames</p>
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:minLength value='1' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name='surgery-29956.2'>
    <xs:sequence>
      <xs:element name='event-details' type='event-details-29940.2' minOccurs='1' maxOccurs='1' />
      <xs:element name='related-cancer-diagnoses' type='related-cancer-diagnoses-37037.1' minOccurs='1' maxOccurs='1' />
      <xs:element name='main-specialty-code' type='xs:string' minOccurs='0' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>The main specialty code of the consultant performing the intervention</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='primary-procedure' type='primaryprocedureopcs-13155.1' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>OPCS code for the primary procedure. Primary procedure is the main procedure carried out.</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='other-procedures' type='procedureopcs-13160.1' minOccurs='0' maxOccurs='unbounded'>
        <xs:annotation>
          <xs:documentation>
            <p>OPCS codes for other procedures. This is a procedure other than the PRIMARY PROCEDURE (OPCS), carried out and recorded for CDS or Hospital Episode Statistics purposes. (This may occur more than once).</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name='event-details-29940.2'>
    <xs:sequence>
      <xs:element name='event-date' type='xs:dateTime' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Date of the clinical event or observation being reported e.g. date biopsy was taken</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='event-reference' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Unique identifier for local record of clinical event or observation</p>
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:minLength value='1' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name='related-cancer-diagnoses-37037.1'>
    <xs:sequence>
      <xs:element name='related-cancer-diagnosis-icd' type='primarydiagnosisicd-12981.1' minOccurs='1' maxOccurs='unbounded'>
        <xs:annotation>
          <xs:documentation>
            <p>Cancer diagnoses that lead to or arise from the reported clinical event. More than one diagnosis can be provided for the same event.</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='related-cancer-diagnosis-snomedct' type='diagnosiscodesnomedct-35537.1' minOccurs='0' maxOccurs='unbounded'>
        <xs:annotation>
          <xs:documentation>
            <p>Optionally, provide the related cancer diagnosis as Snomed CT code as well as the ICD code. Related Cancer Diagnosis is the diagnosis that lead to or arise from the reported clinical event. More than one diagnosis can be provided for the same event.</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name='systemic-anti-cancer-therapy-29957.2'>
    <xs:sequence>
      <xs:element name='event-details' type='event-details-29940.2' minOccurs='1' maxOccurs='1' />
      <xs:element name='related-cancer-diagnoses' type='related-cancer-diagnoses-37037.1' minOccurs='1' maxOccurs='1' />
      <xs:element name='drug-treatment-intent' type='drugtreatmentintent-14409.1' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Treatment intent.</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='drug-regimen' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>The drug regimen prescribed. To be consistent with the National Regimen List.</p>
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:minLength value='1' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name='main-specialty-code' type='xs:string' minOccurs='0' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>The main specialty code of the consultant performing the intervention</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name='radiotherapy-29959.2'>
    <xs:sequence>
      <xs:element name='event-details' type='event-details-29940.2' minOccurs='1' maxOccurs='1' />
      <xs:element name='related-cancer-diagnoses' type='related-cancer-diagnoses-37037.1' minOccurs='1' maxOccurs='1' />
      <xs:element name='radiotherapy-details' type='radiotherapy-details-29970.2' minOccurs='1' maxOccurs='1' />
      <xs:element name='radiotherapy-site' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>OPCS code for site. A classification of part of the body to which the RADIOTHERAPY ACTUAL DOSE is administered.</p>
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:minLength value='1' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name='dose' type='xs:double' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>The total prescribed absorbed radiation dose, measured in Grays, given to the ICRU Reference Point for the whole prescription. http://www.icru.org/home/reports/prescribing-recording-and-reporting-photon-beam-therapy-report-62</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='prescription' type='xs:string' minOccurs='0' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Reference to uploaded copy of prescription document</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='plan' type='xs:string' minOccurs='0' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Reference to uploaded copy of radiotherapy plan</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='radiotherapy-intent' type='radiotherapyintent-14401.1' minOccurs='0' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Intent of radiotherapy</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='main-specialty-code' type='xs:string' minOccurs='0' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>The main specialty code of the consultant performing the intervention</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name='radiotherapy-details-29970.2'>
    <xs:choice>
      <xs:element name='brachytherapy' type='brachytherapy-29971.2' minOccurs='1' maxOccurs='1' />
      <xs:element name='external-beam' type='external-beam-29972.2' minOccurs='1' maxOccurs='1' />
    </xs:choice>
  </xs:complexType>
  <xs:complexType name='brachytherapy-29971.2'>
    <xs:sequence>
      <xs:element name='brachytherapy-type' type='brachytherapytype-13171.1' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>The type of Brachytherapy Treatment Course being used, if applicable.</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name='external-beam-29972.2'>
    <xs:sequence>
      <xs:element name='external-beam-type' type='externalbeamtype-14980.1' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Type of external beam, if applicable. The prescribed type of beam for a Teletherapy Treatment/ Exposure</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='fractions' type='xs:integer' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Dose fractions, if external beam therapy. The total number of Fractions or hyperfraction delivered as part of a RADIOTHERAPY PRESCRIPTION.</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name='brachytherapytype-13171.1' final='restriction'>
    <xs:restriction base='xs:string'>
      <xs:enumeration value='BI'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>Interstitial</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value='BC'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>Intra-cavity</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value='BT'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>Not otherwise specified</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value='US'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>Unsealed Source</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name='diagnosiscodesnomedct-35537.1' final='restriction'>
    <xs:restriction base='xs:string' />
  </xs:simpleType>
  <xs:simpleType name='drugtreatmentintent-14409.1' final='restriction'>
    <xs:restriction base='xs:string'>
      <xs:enumeration value='D'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>Disease Modification</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value='P'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>Palliative</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value='A'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>Adjuvant</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value='C'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>Curative</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value='N'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>Neoadjuvant</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name='externalbeamtype-14980.1' final='restriction'>
    <xs:restriction base='xs:string'>
      <xs:enumeration value='particle_therapy'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>particle_therapy</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value='IMRT'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>IMRT</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value='stereotactic'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>stereotactic</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value='2DXRT'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>2DXRT</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name='nhsnumber-12817.1' final='restriction'>
    <xs:restriction base='xs:token'>
      <xs:maxLength value='10' />
      <xs:minLength value='10' />
      <xs:pattern value='[0-9]{10}' />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name='primarydiagnosisicd-12981.1' final='restriction'>
    <xs:restriction base='xs:string' />
  </xs:simpleType>
  <xs:simpleType name='primaryprocedureopcs-13155.1' final='restriction'>
    <xs:restriction base='xs:string' />
  </xs:simpleType>
  <xs:simpleType name='procedureopcs-13160.1' final='restriction'>
    <xs:restriction base='xs:string' />
  </xs:simpleType>
  <xs:simpleType name='radiotherapyintent-14401.1' final='restriction'>
    <xs:restriction base='xs:string'>
      <xs:enumeration value='01'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>Anti-cancer</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value='02'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>Other</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value='03'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>Palliative</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== freshehrteam/GEL/docs/original datasets/Cancer Schemas v2.0.0 FINAL/Cancer Schemas v2.0.0 EXAMPLES/InterventionsCancer-v2.0.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<gelCAN:interventions xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:gelCAN="https://genomicsengland.co.uk/xsd/cancer/2.0.0"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://genomicsengland.co.uk/xsd/cancer/2.0.0 file:/Users/genomicsengland/Documents/Cancer/MainProgrammeCancer/Cancer%20Schemas%20v2.0.0%20FINAL/InterventionsCancer-v2.0.0.xsd">
    <gelCAN:metadata>
        <gelCAN:schema-name>InterventionsCancer</gelCAN:schema-name>
        <gelCAN:schema-version>2.0.0</gelCAN:schema-version>
        <gelCAN:date>2006-05-04</gelCAN:date>
        <gelCAN:source-organisation>source-organisation0</gelCAN:source-organisation>
        <gelCAN:source-system>source-system0</gelCAN:source-system>
        <gelCAN:local-report-id>local-report-id0</gelCAN:local-report-id>
    </gelCAN:metadata>
    <gelCAN:subject>
        <gelCAN:participant-identifiers>
            <gelCAN:participant-id>participant-id0</gelCAN:participant-id>
            <gelCAN:date-of-birth>2006-05-04</gelCAN:date-of-birth>
            <gelCAN:nhs-number>0000000000</gelCAN:nhs-number>
            <gelCAN:chi-number>chi-number0</gelCAN:chi-number>
            <gelCAN:surname>surname0</gelCAN:surname>
            <gelCAN:forenames>forenames0</gelCAN:forenames>
        </gelCAN:participant-identifiers>
        <gelCAN:surgery>
            <gelCAN:event-details>
                <gelCAN:event-date>2006-05-04T18:13:51.0</gelCAN:event-date>
                <gelCAN:event-reference>event-reference0</gelCAN:event-reference>
            </gelCAN:event-details>
            <gelCAN:related-cancer-diagnoses>
                <gelCAN:related-cancer-diagnosis-icd>related-cancer-diagnosis-icd0</gelCAN:related-cancer-diagnosis-icd>
                <gelCAN:related-cancer-diagnosis-icd>related-cancer-diagnosis-icd1</gelCAN:related-cancer-diagnosis-icd>
                <gelCAN:related-cancer-diagnosis-snomedct>related-cancer-diagnosis-snomedct0</gelCAN:related-cancer-diagnosis-snomedct>
                <gelCAN:related-cancer-diagnosis-snomedct>related-cancer-diagnosis-snomedct1</gelCAN:related-cancer-diagnosis-snomedct>
            </gelCAN:related-cancer-diagnoses>
            <gelCAN:main-specialty-code>main-specialty-code0</gelCAN:main-specialty-code>
            <gelCAN:primary-procedure>primary-procedure0</gelCAN:primary-procedure>
            <gelCAN:other-procedures>other-procedures0</gelCAN:other-procedures>
            <gelCAN:other-procedures>other-procedures1</gelCAN:other-procedures>
        </gelCAN:surgery>
        <gelCAN:surgery>
            <gelCAN:event-details>
                <gelCAN:event-date>2006-05-04T18:13:51.0</gelCAN:event-date>
                <gelCAN:event-reference>event-reference1</gelCAN:event-reference>
            </gelCAN:event-details>
            <gelCAN:related-cancer-diagnoses>
                <gelCAN:related-cancer-diagnosis-icd>related-cancer-diagnosis-icd2</gelCAN:related-cancer-diagnosis-icd>
                <gelCAN:related-cancer-diagnosis-icd>related-cancer-diagnosis-icd3</gelCAN:related-cancer-diagnosis-icd>
                <gelCAN:related-cancer-diagnosis-snomedct>related-cancer-diagnosis-snomedct2</gelCAN:related-cancer-diagnosis-snomedct>
                <gelCAN:related-cancer-diagnosis-snomedct>related-cancer-diagnosis-snomedct3</gelCAN:related-cancer-diagnosis-snomedct>
            </gelCAN:related-cancer-diagnoses>
            <gelCAN:main-specialty-code>main-specialty-code1</gelCAN:main-specialty-code>
            <gelCAN:primary-procedure>primary-procedure1</gelCAN:primary-procedure>
            <gelCAN:other-procedures>other-procedures2</gelCAN:other-procedures>
            <gelCAN:other-procedures>other-procedures3</gelCAN:other-procedures>
        </gelCAN:surgery>
        <gelCAN:systemic-anti-cancer-therapy>
            <gelCAN:event-details>
                <gelCAN:event-date>2006-05-04T18:13:51.0</gelCAN:event-date>
                <gelCAN:event-reference>event-reference2</gelCAN:event-reference>
            </gelCAN:event-details>
            <gelCAN:related-cancer-diagnoses>
                <gelCAN:related-cancer-diagnosis-icd>related-cancer-diagnosis-icd4</gelCAN:related-cancer-diagnosis-icd>
                <gelCAN:related-cancer-diagnosis-icd>related-cancer-diagnosis-icd5</gelCAN:related-cancer-diagnosis-icd>
                <gelCAN:related-cancer-diagnosis-snomedct>related-cancer-diagnosis-snomedct4</gelCAN:related-cancer-diagnosis-snomedct>
                <gelCAN:related-cancer-diagnosis-snomedct>related-cancer-diagnosis-snomedct5</gelCAN:related-cancer-diagnosis-snomedct>
            </gelCAN:related-cancer-diagnoses>
            <gelCAN:drug-treatment-intent>D</gelCAN:drug-treatment-intent>
            <gelCAN:drug-regimen>drug-regimen0</gelCAN:drug-regimen>
            <gelCAN:main-specialty-code>main-specialty-code2</gelCAN:main-specialty-code>
        </gelCAN:systemic-anti-cancer-therapy>
        <gelCAN:systemic-anti-cancer-therapy>
            <gelCAN:event-details>
                <gelCAN:event-date>2006-05-04T18:13:51.0</gelCAN:event-date>
                <gelCAN:event-reference>event-reference3</gelCAN:event-reference>
            </gelCAN:event-details>
            <gelCAN:related-cancer-diagnoses>
                <gelCAN:related-cancer-diagnosis-icd>related-cancer-diagnosis-icd6</gelCAN:related-cancer-diagnosis-icd>
                <gelCAN:related-cancer-diagnosis-icd>related-cancer-diagnosis-icd7</gelCAN:related-cancer-diagnosis-icd>
                <gelCAN:related-cancer-diagnosis-snomedct>related-cancer-diagnosis-snomedct6</gelCAN:related-cancer-diagnosis-snomedct>
                <gelCAN:related-cancer-diagnosis-snomedct>related-cancer-diagnosis-snomedct7</gelCAN:related-cancer-diagnosis-snomedct>
            </gelCAN:related-cancer-diagnoses>
            <gelCAN:drug-treatment-intent>D</gelCAN:drug-treatment-intent>
            <gelCAN:drug-regimen>drug-regimen1</gelCAN:drug-regimen>
            <gelCAN:main-specialty-code>main-specialty-code3</gelCAN:main-specialty-code>
        </gelCAN:systemic-anti-cancer-therapy>
        <gelCAN:radiotherapy>
            <gelCAN:event-details>
                <gelCAN:event-date>2006-05-04T18:13:51.0</gelCAN:event-date>
                <gelCAN:event-reference>event-reference4</gelCAN:event-reference>
            </gelCAN:event-details>
            <gelCAN:related-cancer-diagnoses>
                <gelCAN:related-cancer-diagnosis-icd>related-cancer-diagnosis-icd8</gelCAN:related-cancer-diagnosis-icd>
                <gelCAN:related-cancer-diagnosis-icd>related-cancer-diagnosis-icd9</gelCAN:related-cancer-diagnosis-icd>
                <gelCAN:related-cancer-diagnosis-snomedct>related-cancer-diagnosis-snomedct8</gelCAN:related-cancer-diagnosis-snomedct>
                <gelCAN:related-cancer-diagnosis-snomedct>related-cancer-diagnosis-snomedct9</gelCAN:related-cancer-diagnosis-snomedct>
            </gelCAN:related-cancer-diagnoses>
            <gelCAN:radiotherapy-details>
                <gelCAN:external-beam>
                    <gelCAN:external-beam-type>particle_therapy</gelCAN:external-beam-type>
                    <gelCAN:fractions>0</gelCAN:fractions>
                </gelCAN:external-beam>
            </gelCAN:radiotherapy-details>
            <gelCAN:radiotherapy-site>radiotherapy-site0</gelCAN:radiotherapy-site>
            <gelCAN:dose>0</gelCAN:dose>
            <gelCAN:prescription>prescription0</gelCAN:prescription>
            <gelCAN:plan>plan0</gelCAN:plan>
            <gelCAN:radiotherapy-intent>01</gelCAN:radiotherapy-intent>
            <gelCAN:main-specialty-code>main-specialty-code4</gelCAN:main-specialty-code>
        </gelCAN:radiotherapy>
        <gelCAN:radiotherapy>
            <gelCAN:event-details>
                <gelCAN:event-date>2006-05-04T18:13:51.0</gelCAN:event-date>
                <gelCAN:event-reference>event-reference5</gelCAN:event-reference>
            </gelCAN:event-details>
            <gelCAN:related-cancer-diagnoses>
                <gelCAN:related-cancer-diagnosis-icd>related-cancer-diagnosis-icd10</gelCAN:related-cancer-diagnosis-icd>
                <gelCAN:related-cancer-diagnosis-icd>related-cancer-diagnosis-icd11</gelCAN:related-cancer-diagnosis-icd>
                <gelCAN:related-cancer-diagnosis-snomedct>related-cancer-diagnosis-snomedct10</gelCAN:related-cancer-diagnosis-snomedct>
                <gelCAN:related-cancer-diagnosis-snomedct>related-cancer-diagnosis-snomedct11</gelCAN:related-cancer-diagnosis-snomedct>
            </gelCAN:related-cancer-diagnoses>
            <gelCAN:radiotherapy-details>
                <gelCAN:brachytherapy>
                    <gelCAN:brachytherapy-type>BI</gelCAN:brachytherapy-type>
                </gelCAN:brachytherapy>
            </gelCAN:radiotherapy-details>
            <gelCAN:radiotherapy-site>radiotherapy-site1</gelCAN:radiotherapy-site>
            <gelCAN:dose>0</gelCAN:dose>
            <gelCAN:prescription>prescription1</gelCAN:prescription>
            <gelCAN:plan>plan1</gelCAN:plan>
            <gelCAN:radiotherapy-intent>01</gelCAN:radiotherapy-intent>
            <gelCAN:main-specialty-code>main-specialty-code5</gelCAN:main-specialty-code>
        </gelCAN:radiotherapy>
    </gelCAN:subject>
    <gelCAN:subject>
        <gelCAN:participant-identifiers>
            <gelCAN:participant-id>participant-id1</gelCAN:participant-id>
            <gelCAN:date-of-birth>2006-05-04</gelCAN:date-of-birth>
            <gelCAN:nhs-number>0000000000</gelCAN:nhs-number>
            <gelCAN:chi-number>chi-number1</gelCAN:chi-number>
            <gelCAN:surname>surname1</gelCAN:surname>
            <gelCAN:forenames>forenames1</gelCAN:forenames>
        </gelCAN:participant-identifiers>
        <gelCAN:surgery>
            <gelCAN:event-details>
                <gelCAN:event-date>2006-05-04T18:13:51.0</gelCAN:event-date>
