=== freshehrteam/GEL/docs/original datasets/Cancer Schemas v2.0.0 FINAL/DeathsCancer-v2.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:vc='http://www.w3.org/2007/XMLSchema-versioning' xmlns:gelCAN='https://genomicsengland.co.uk/xsd/cancer/2.0.0' xmlns='https://genomicsengland.co.uk/xsd/cancer/2.0.0' targetNamespace='https://genomicsengland.co.uk/xsd/cancer/2.0.0' vc:minVersion='1.1' elementFormDefault='qualified'>
  <xs:annotation>
    <xs:documentation>
      <h1>DeathsCancer</h1>
      <p>Version:2.0.0</p>
      <p>Description:Main Programme Death Schema</p>
      <p>Generated: 2016-01-25T16:49:19.965+0000</p>
    </xs:documentation>
  </xs:annotation>
  <xs:element name='deaths'>
    <xs:complexType>
      <xs:sequence>
        <xs:element name='metadata' type='metadata' minOccurs='1' maxOccurs='1' />
        <xs:element name='subject' type='subject-15065.4' minOccurs='1' maxOccurs='unbounded' />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name='metadata'>
    <xs:sequence>
      <xs:element name='schema-name' minOccurs='1' maxOccurs='1'>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:enumeration value='DeathsCancer' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name='schema-version' minOccurs='1' maxOccurs='1'>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:enumeration value='2.0.0' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name='date' type='xs:date' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>The date that this file was generated</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='source-organisation' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>ODS code of the source organisation within the GMC sending the message</p>
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:minLength value='1' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name='source-system' type='xs:string' minOccurs='0' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Source system. Optional but may be used to supply source with information if there are any issues with the submitted XML.</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='local-report-id' type='xs:string' minOccurs='0' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Source system report Id. Optional but may be used to supply source with information if there are any issues with the submitted XML.</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name='subject-15065.4'>
    <xs:sequence>
      <xs:element name='participant-identifiers' type='participant-identifiers-29330.2' minOccurs='1' maxOccurs='1' />
      <xs:element name='death' type='death-37196.1' minOccurs='1' maxOccurs='1' />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name='participant-identifiers-29330.2'>
    <xs:sequence>
      <xs:element name='participant-id' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Participant Identifier (supplied by Genomics England)</p>
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:minLength value='1' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name='date-of-birth' type='xs:date' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>The participant&amp;apos;s date of birth</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='nhs-number' type='nhsnumber-12817.1' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Validated NHS number for participant</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='chi-number' type='xs:string' minOccurs='0' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Scottish Community Health Index (CHI) number for participant</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='surname' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>The participant&amp;apos;s surname</p>
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:minLength value='1' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name='forenames' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>The participant&amp;apos;s forenames</p>
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:minLength value='1' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name='death-37196.1'>
    <xs:sequence>
      <xs:element name='event-details' type='event-details-29940.2' minOccurs='1' maxOccurs='1' />
      <xs:element name='related-cancer-diagnoses' type='related-cancer-diagnoses-37037.1' minOccurs='1' maxOccurs='1' />
      <xs:element name='death-location' type='deathlocation-12783.1' minOccurs='0' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Location of death</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='significant' type='xs:string' minOccurs='0' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Significant condition not leading to death. Coded according to the International Classification of Diseases (ICD) code of the condition leading to death as recorded on the death certificate.</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='condition' type='xs:string' minOccurs='0' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Condition leading to death. Coded according to the International Classification of Diseases (ICD) code of the condition leading to death as recorded on the death certificate.</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='immediate-cause' type='xs:string' minOccurs='0' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Immediate cause of death. Coded according to the International Classification of Diseases (ICD) code of the condition leading to death as recorded on the death certificate.</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='underlying-cause' type='xs:string' minOccurs='0' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Underlying cause of death. Coded according to the International Classification of Diseases (ICD) code of the condition leading to death as recorded on the death certificate.</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name='event-details-29940.2'>
    <xs:sequence>
      <xs:element name='event-date' type='xs:dateTime' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Date of the clinical event or observation being reported e.g. date biopsy was taken</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='event-reference' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Unique identifier for local record of clinical event or observation</p>
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:minLength value='1' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name='related-cancer-diagnoses-37037.1'>
    <xs:sequence>
      <xs:element name='related-cancer-diagnosis-icd' type='primarydiagnosisicd-12981.1' minOccurs='1' maxOccurs='unbounded'>
        <xs:annotation>
          <xs:documentation>
            <p>Cancer diagnoses that lead to or arise from the reported clinical event. More than one diagnosis can be provided for the same event.</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='related-cancer-diagnosis-snomedct' type='diagnosiscodesnomedct-35537.1' minOccurs='0' maxOccurs='unbounded'>
        <xs:annotation>
          <xs:documentation>
            <p>Optionally, provide the related cancer diagnosis as Snomed CT code as well as the ICD code. Related Cancer Diagnosis is the diagnosis that lead to or arise from the reported clinical event. More than one diagnosis can be provided for the same event.</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name='deathlocation-12783.1' final='restriction'>
    <xs:restriction base='xs:string'>
      <xs:enumeration value='3'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>Voluntary hospice / Specialist Palliative Care unit</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value='2'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>NHS hospice / Specialist Palliative Care unit</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value='1'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>Hospital</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value='6'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>Other</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value='5'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>Care Home</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value='4'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>PATIENT's own home</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name='diagnosiscodesnomedct-35537.1' final='restriction'>
    <xs:restriction base='xs:string' />
  </xs:simpleType>
  <xs:simpleType name='nhsnumber-12817.1' final='restriction'>
    <xs:restriction base='xs:token'>
      <xs:maxLength value='10' />
      <xs:minLength value='10' />
      <xs:pattern value='[0-9]{10}' />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name='primarydiagnosisicd-12981.1' final='restriction'>
    <xs:restriction base='xs:string' />
  </xs:simpleType>
</xs:schema>

=== freshehrteam/GEL/docs/cancer/original datasets/Cancer Schemas v2.0.0 FINAL/Cancer Schemas v2.0.0 EXAMPLES/DeathsCancer-v2.0.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<gelCAN:deaths xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:gelCAN="https://genomicsengland.co.uk/xsd/cancer/2.0.0"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://genomicsengland.co.uk/xsd/cancer/2.0.0 file:/Users/genomicsengland/Documents/Cancer/MainProgrammeCancer/Cancer%20Schemas%20v2.0.0%20FINAL/DeathsCancer-v2.0.0.xsd">
    <gelCAN:metadata>
        <gelCAN:schema-name>DeathsCancer</gelCAN:schema-name>
        <gelCAN:schema-version>2.0.0</gelCAN:schema-version>
        <gelCAN:date>2006-05-04</gelCAN:date>
        <gelCAN:source-organisation>source-organisation0</gelCAN:source-organisation>
        <gelCAN:source-system>source-system0</gelCAN:source-system>
        <gelCAN:local-report-id>local-report-id0</gelCAN:local-report-id>
    </gelCAN:metadata>
    <gelCAN:subject>
        <gelCAN:participant-identifiers>
            <gelCAN:participant-id>participant-id0</gelCAN:participant-id>
            <gelCAN:date-of-birth>2006-05-04</gelCAN:date-of-birth>
            <gelCAN:nhs-number>0000000000</gelCAN:nhs-number>
            <gelCAN:chi-number>chi-number0</gelCAN:chi-number>
            <gelCAN:surname>surname0</gelCAN:surname>
            <gelCAN:forenames>forenames0</gelCAN:forenames>
        </gelCAN:participant-identifiers>
        <gelCAN:death>
            <gelCAN:event-details>
                <gelCAN:event-date>2006-05-04T18:13:51.0</gelCAN:event-date>
                <gelCAN:event-reference>event-reference0</gelCAN:event-reference>
            </gelCAN:event-details>
            <gelCAN:related-cancer-diagnoses>
                <gelCAN:related-cancer-diagnosis-icd>related-cancer-diagnosis-icd0</gelCAN:related-cancer-diagnosis-icd>
                <gelCAN:related-cancer-diagnosis-icd>related-cancer-diagnosis-icd1</gelCAN:related-cancer-diagnosis-icd>
                <gelCAN:related-cancer-diagnosis-snomedct>related-cancer-diagnosis-snomedct0</gelCAN:related-cancer-diagnosis-snomedct>
                <gelCAN:related-cancer-diagnosis-snomedct>related-cancer-diagnosis-snomedct1</gelCAN:related-cancer-diagnosis-snomedct>
            </gelCAN:related-cancer-diagnoses>
            <gelCAN:death-location>3</gelCAN:death-location>
            <gelCAN:significant>significant0</gelCAN:significant>
            <gelCAN:condition>condition0</gelCAN:condition>
            <gelCAN:immediate-cause>immediate-cause0</gelCAN:immediate-cause>
            <gelCAN:underlying-cause>underlying-cause0</gelCAN:underlying-cause>
        </gelCAN:death>
    </gelCAN:subject>
    <gelCAN:subject>
        <gelCAN:participant-identifiers>
            <gelCAN:participant-id>participant-id1</gelCAN:participant-id>
            <gelCAN:date-of-birth>2006-05-04</gelCAN:date-of-birth>
            <gelCAN:nhs-number>0000000000</gelCAN:nhs-number>
            <gelCAN:chi-number>chi-number1</gelCAN:chi-number>
            <gelCAN:surname>surname1</gelCAN:surname>
            <gelCAN:forenames>forenames1</gelCAN:forenames>
        </gelCAN:participant-identifiers>
        <gelCAN:death>
            <gelCAN:event-details>
                <gelCAN:event-date>2006-05-04T18:13:51.0</gelCAN:event-date>
                <gelCAN:event-reference>event-reference1</gelCAN:event-reference>
            </gelCAN:event-details>
            <gelCAN:related-cancer-diagnoses>
                <gelCAN:related-cancer-diagnosis-icd>related-cancer-diagnosis-icd2</gelCAN:related-cancer-diagnosis-icd>
                <gelCAN:related-cancer-diagnosis-icd>related-cancer-diagnosis-icd3</gelCAN:related-cancer-diagnosis-icd>
                <gelCAN:related-cancer-diagnosis-snomedct>related-cancer-diagnosis-snomedct2</gelCAN:related-cancer-diagnosis-snomedct>
                <gelCAN:related-cancer-diagnosis-snomedct>related-cancer-diagnosis-snomedct3</gelCAN:related-cancer-diagnosis-snomedct>
            </gelCAN:related-cancer-diagnoses>
            <gelCAN:death-location>3</gelCAN:death-location>
            <gelCAN:significant>significant1</gelCAN:significant>
            <gelCAN:condition>condition1</gelCAN:condition>
            <gelCAN:immediate-cause>immediate-cause1</gelCAN:immediate-cause>
            <gelCAN:underlying-cause>underlying-cause1</gelCAN:underlying-cause>
        </gelCAN:death>
    </gelCAN:subject>
</gelCAN:deaths>
