=== freshehrteam/GEL/docs/original datasets/Cancer Schemas v2.0.0 FINAL/WithdrawalsCancer-v2.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:vc='http://www.w3.org/2007/XMLSchema-versioning' xmlns:gelCAN='https://genomicsengland.co.uk/xsd/cancer/2.0.0' xmlns='https://genomicsengland.co.uk/xsd/cancer/2.0.0' targetNamespace='https://genomicsengland.co.uk/xsd/cancer/2.0.0' vc:minVersion='1.1' elementFormDefault='qualified'>
  <xs:annotation>
    <xs:documentation>
      <h1>WithdrawalsCancer</h1>
      <p>Version:2.0.0</p>
      <p>Description:Main Programme Consent Withdrawal Schema</p>
      <p>Generated: 2016-01-25T16:49:12.194+0000</p>
    </xs:documentation>
  </xs:annotation>
  <xs:element name='withdrawals'>
    <xs:complexType>
      <xs:sequence>
        <xs:element name='metadata' type='metadata' minOccurs='1' maxOccurs='1' />
        <xs:element name='subject' type='subject-15039.5' minOccurs='1' maxOccurs='unbounded' />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name='metadata'>
    <xs:sequence>
      <xs:element name='schema-name' minOccurs='1' maxOccurs='1'>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:enumeration value='WithdrawalsCancer' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name='schema-version' minOccurs='1' maxOccurs='1'>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:enumeration value='2.0.0' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name='date' type='xs:date' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>The date that this file was generated</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='source-organisation' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>ODS code of the source organisation within the GMC sending the message</p>
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:minLength value='1' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name='source-system' type='xs:string' minOccurs='0' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Source system. Optional but may be used to supply source with information if there are any issues with the submitted XML.</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='local-report-id' type='xs:string' minOccurs='0' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Source system report Id. Optional but may be used to supply source with information if there are any issues with the submitted XML.</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name='subject-15039.5'>
    <xs:sequence>
      <xs:element name='participant-identifiers' type='participant-identifiers-29330.2' minOccurs='1' maxOccurs='1' />
      <xs:element name='withdrawal' type='withdrawal-37038.1' minOccurs='1' maxOccurs='1' />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name='participant-identifiers-29330.2'>
    <xs:sequence>
      <xs:element name='participant-id' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Participant Identifier (supplied by Genomics England)</p>
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:minLength value='1' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name='date-of-birth' type='xs:date' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>The participant&amp;apos;s date of birth</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='nhs-number' type='nhsnumber-12817.1' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Validated NHS number for participant</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='chi-number' type='xs:string' minOccurs='0' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Scottish Community Health Index (CHI) number for participant</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='surname' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>The participant&amp;apos;s surname</p>
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:minLength value='1' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name='forenames' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>The participant&amp;apos;s forenames</p>
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:minLength value='1' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name='withdrawal-37038.1'>
    <xs:sequence>
      <xs:element name='event-details' type='event-details-29940.2' minOccurs='1' maxOccurs='1' />
      <xs:element name='date-of-withdrawal-of-consent' type='xs:date' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>The date withdrawal occurred</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='withdrawal-form' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Filename of uploaded copy of scanned withdrawal form pdf - requested format is [ParticipantId]_withdrawal_[TimeStamp].pdf</p>
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:minLength value='1' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name='withdrawal-option' type='consentwithdrawaloptions-12733.1' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Indicating full or partial withdrawal</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='name-and-version-of-the-withdrawal-form-used' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Name and Version of form used - list of names and versions available from genomicsengland.co.uk/library-and-resources/</p>
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:minLength value='1' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name='person-reporting-withdrawal' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Full name, including forenames and surname, of person reporting withdrawal.</p>
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:minLength value='1' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name='event-details-29940.2'>
    <xs:sequence>
      <xs:element name='event-date' type='xs:dateTime' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Date of the clinical event or observation being reported e.g. date biopsy was taken</p>
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name='event-reference' minOccurs='1' maxOccurs='1'>
        <xs:annotation>
          <xs:documentation>
            <p>Unique identifier for local record of clinical event or observation</p>
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base='xs:string'>
            <xs:minLength value='1' />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name='consentwithdrawaloptions-12733.1' final='restriction'>
    <xs:restriction base='xs:string'>
      <xs:enumeration value='FULL_WITHDRAWAL'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>OPTION 2: FULL WITHDRAWAL: No further use</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value='PARTIAL_WITHDRAWAL'>
        <xs:annotation>
          <xs:appinfo>
            <display-text>OPTION 1: PARTIAL WITHDRAWAL: No further contact</display-text>
          </xs:appinfo>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name='nhsnumber-12817.1' final='restriction'>
    <xs:restriction base='xs:token'>
      <xs:maxLength value='10' />
      <xs:minLength value='10' />
      <xs:pattern value='[0-9]{10}' />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== freshehrteam/GEL/docs/cancer/original datasets/Cancer Schemas v2.0.0 FINAL/Cancer Schemas v2.0.0 EXAMPLES/WithdrawalsCancer-v2.0.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<gelCAN:withdrawals xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:gelCAN="https://genomicsengland.co.uk/xsd/cancer/2.0.0"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://genomicsengland.co.uk/xsd/cancer/2.0.0 file:/Users/genomicsengland/Documents/Cancer/MainProgrammeCancer/Cancer%20Schemas%20v2.0.0%20FINAL/WithdrawalsCancer-v2.0.0.xsd">
    <gelCAN:metadata>
        <gelCAN:schema-name>WithdrawalsCancer</gelCAN:schema-name>
        <gelCAN:schema-version>2.0.0</gelCAN:schema-version>
        <gelCAN:date>2006-05-04</gelCAN:date>
        <gelCAN:source-organisation>source-organisation0</gelCAN:source-organisation>
        <gelCAN:source-system>source-system0</gelCAN:source-system>
        <gelCAN:local-report-id>local-report-id0</gelCAN:local-report-id>
    </gelCAN:metadata>
    <gelCAN:subject>
        <gelCAN:participant-identifiers>
            <gelCAN:participant-id>participant-id0</gelCAN:participant-id>
            <gelCAN:date-of-birth>2006-05-04</gelCAN:date-of-birth>
            <gelCAN:nhs-number>0000000000</gelCAN:nhs-number>
            <gelCAN:chi-number>chi-number0</gelCAN:chi-number>
            <gelCAN:surname>surname0</gelCAN:surname>
            <gelCAN:forenames>forenames0</gelCAN:forenames>
        </gelCAN:participant-identifiers>
        <gelCAN:withdrawal>
            <gelCAN:event-details>
                <gelCAN:event-date>2006-05-04T18:13:51.0</gelCAN:event-date>
                <gelCAN:event-reference>event-reference0</gelCAN:event-reference>
            </gelCAN:event-details>
            <gelCAN:date-of-withdrawal-of-consent>2006-05-04</gelCAN:date-of-withdrawal-of-consent>
            <gelCAN:withdrawal-form>withdrawal-form0</gelCAN:withdrawal-form>
            <gelCAN:withdrawal-option>FULL_WITHDRAWAL</gelCAN:withdrawal-option>
            <gelCAN:name-and-version-of-the-withdrawal-form-used>name-and-version-of-the-withdrawal-form-used0</gelCAN:name-and-version-of-the-withdrawal-form-used>
            <gelCAN:person-reporting-withdrawal>person-reporting-withdrawal0</gelCAN:person-reporting-withdrawal>
        </gelCAN:withdrawal>
    </gelCAN:subject>
    <gelCAN:subject>
        <gelCAN:participant-identifiers>
            <gelCAN:participant-id>participant-id1</gelCAN:participant-id>
            <gelCAN:date-of-birth>2006-05-04</gelCAN:date-of-birth>
            <gelCAN:nhs-number>0000000000</gelCAN:nhs-number>
            <gelCAN:chi-number>chi-number1</gelCAN:chi-number>
            <gelCAN:surname>surname1</gelCAN:surname>
            <gelCAN:forenames>forenames1</gelCAN:forenames>
        </gelCAN:participant-identifiers>
        <gelCAN:withdrawal>
            <gelCAN:event-details>
                <gelCAN:event-date>2006-05-04T18:13:51.0</gelCAN:event-date>
                <gelCAN:event-reference>event-reference1</gelCAN:event-reference>
            </gelCAN:event-details>
            <gelCAN:date-of-withdrawal-of-consent>2006-05-04</gelCAN:date-of-withdrawal-of-consent>
            <gelCAN:withdrawal-form>withdrawal-form1</gelCAN:withdrawal-form>
            <gelCAN:withdrawal-option>FULL_WITHDRAWAL</gelCAN:withdrawal-option>
            <gelCAN:name-and-version-of-the-withdrawal-form-used>name-and-version-of-the-withdrawal-form-used1</gelCAN:name-and-version-of-the-withdrawal-form-used>
            <gelCAN:person-reporting-withdrawal>person-reporting-withdrawal1</gelCAN:person-reporting-withdrawal>
        </gelCAN:withdrawal>
    </gelCAN:subject>
</gelCAN:withdrawals>
